title: Vic Debsoc
description: |-
  Victoria University of Wellington Debating Society
  Club Nights - KK303, 6:30pm, every Wednesday
room: "KK303"
time: "6:30"
day: "Wednesday"
signup_link: "https://forms.gle/Fa95xGR3PVTZzybq9"
twitter_username: vicdebsoc
url: "https://vicdebsoc.org.nz"

#
#   Technical Details below, only edit if you know what you're doing
#   Jekyll Docs: https://jekyllrb.com/docs
#   StaticJsCMS: https://www.staticcms.org/docs/intro
#   Debsoc Docs: TODO
#

timezone: Pacific/Auckland
safe: true

collections:
  events:
    title: Events
    permalink: /events/:year-:month-:day-:slug
    sort_by: event-start
    output: true
  blog:
    title: Blog
    permalink: /blog/:year-:month-:day-:slug
    output: true
  resources:
    title: Resources
    permalink: /resources/:path
    output: true

# https://github.com/avillafiorita/jekyll-datapage_gen
page_gen-dirs: false
page_gen:
  - data: 'records_userprofile'
    template: 'record-user'
    name_expr: record['first_name'] + "_" + record['last_name']
  
  - date: 'records_tournamentevent'
    template: 'record-user'   # TODO
    name_expr: # TODO:
      # I'd like for it to be tournamentName-year, but you can't bring in external data,
      #  so maybe I just have tournament name then break it out by year, although that's a tad inelegant
