title: Vic Debsoc
description: |-
  Victoria University of Wellington Debating Society
  Club Nights - KK303, 6:30pm, every Wednesday
# TODO more?
# twitter_username: vicdebsoc

#
#   Technical Details below, only edit if you know what you're doing
#   Jekyll Docs: https://jekyllrb.com/docs
#   TODO CMS: TODO
#   Debsoc Docs: TODO
#

timezone: Pacific/Auckland
safe: true

collections:
  events:
    title: Events
    permalink: /events/:path  # TODO, maybe something better?
    sort_by: event-start  # TODO
    output: true
  blog:
    title:
    title: Blog
    permalink: /blog/:path # TODO
    output: true

url: "https://vicdebsoc.org.nz"

# Build settings
# TODO: RSS feed