backend:
  name: git-gateway

local_backend: 
  allowed_hosts: ['localhost', '127.0.0.1', '192.168.50.172']

locale: en_nz
logo_url: '/images/logo.png'
media_folder: '/static/uploads'  # Where to store the uploads
public_folder: '/uploads'         # Where they can be accessed from on the server

editor:
  size: 'half'

collections:
  - name: 'blog' # Used in 
    label: 'Blog' # Used in the UI
    label_singular: 'Post'
    folder: 'content/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    sortable_fields:
      fields: []
      default:
        field: 'commit_date'
        direction: Descending
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', format: "yyyy-MM-dd x", date_format: "PPPP", time_format: false }
      - &Markdown
        label: 'Body'
        name: 'body'
        widget: 'markdown'
        toolbar_buttons:
          main:
            - bold
            - italic
            - strikethrough
            - code
            - font
            - unordered-list
            - ordered-list
            # - shortcode
              # - Link to other page (https://jekyllrb.com/docs/liquid/tags/#linking-to-posts)
              # - Accordion?
            - label: Insert
              groups:
                - items:
                    - blockquote
                    - insert-table
                - items:
                    - image
                    - file-link

  - name: 'events'
    label: 'Events'
    label_singular: 'Event'
    folder: 'content/events'
    create: true
    summary_fields: ['title', 'start', 'end']
    sortable_fields:
      fields: []
      default:
        field: start
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'event' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'publishDate', format: "yyyy-MM-dd x", date_format: "PPPP", time_format: false }
      - { label: 'Excerpt', name: 'excerpt', type: 'text' }
      - { label: 'Location', name: 'location', widget: 'map' }
      - { label: 'Event Start', name: 'start', widget: 'date', format: "yyyy-MM-dd HH:mm x", date_format: "PPPP", time_format: 'HH:mm' }
      - { label: 'Event End', name: 'expiryDate', widget: 'datetime', format: "yyyy-MM-dd HH:mm x", date_format: "PPPP", time_format: 'HH:mm' }
      - *Markdown

  - name: 'resources'
    label: 'Resources'
    label_singular: 'Resource'
    folder: 'content/resources'
    create: true
    summary_fields: ['title', 'excerpt']
    sortable_fields:
      fields: ['commit_date', 'title']
      default:
        field: 'commit_date'
        direction: Descending
    slug: '{{slug}}'
    fields: 
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'resource' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Cover Image', name: 'cover_image', widget: 'image' }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', format: "yyyy-MM-dd x", date_format: "PPPP", time_format: false }
      - { label: 'Excerpt', name: 'excerpt', type: 'text' }
      - *Markdown
    
  - name: 'pages'
    label: 'Pages'
    editor:
      size: half
    files:
      - name: 'home'
        label: 'Home'
        file: '/layouts/index.html.html'
        fields:
          - { label: 'Code', name: 'code', widget: 'code', default_language: 'html'}
      - name: 'about'
        label: 'About'
        file: '/content/about.md'
        fields:
          - *Markdown
