backend:
  name: test-repo

locale: en_nz

media_folder: 'images/uploads' # Media files will be stored in the repo under images/uploads

collections:
  - name: 'blog' # Used in routes
    label: 'Blog' # Used in the UI
    folder: '_blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      size: 'ha lf'
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: "yyyy-MM-dd x", date_format: "PPPP", time_format: false}
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        toolbar_buttons:
          main:
            - bold
            - italic
            - strikethrough
            - code
            - font
            - unordered-list
            - ordered-list
            # - shortcode     # TODO: Maybe add some?
            - label: Insert
              groups:
                - items:
                    - blockquote
                    - insert-table
                - items:
                    - image
                    - file-link
