backend:
  name: test-repo

locale: en_nz
logo_url: http://127.0.0.1:4000/images/logo.png
media_folder: 'images/uploads' # Media files will be stored in the repo under images/uploads

collections:
  - name: 'blog' # Used in 
    label: 'Blog' # Used in the UI
    label_singular: 'Post'
    folder: '_blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: "yyyy-MM-dd x", date_format: "PPPP", time_format: false }
      - &Markdown
        label: 'Body'
        name: 'body'
        widget: 'markdown'
        toolbar_buttons:
          main:
            - bold
            - italic
            - strikethrough
            - code
            - font
            - unordered-list
            - ordered-list
            # - shortcode     # TODO: Maybe add some?
            - label: Insert
              groups:
                - items:
                    - blockquote
                    - insert-table
                - items:
                    - image
                    - file-link

  - name: 'events'
    label: 'Events'
    label_singular: 'Event'
    folder: '_events'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: "yyyy-MM-dd x", date_format: "PPPP", time_format: false }
      - { label: 'Excerpt', name: 'excerpt', type: 'text' }
      - { label: 'Location', name: 'location', widget: 'map' }
      - { label: 'Event Start', name: 'start', widget: 'datetime', format: "yyyy-MM-dd HH:mm x", date_format: "PPPP", time_format: 'HH:mm' }
      - { label: 'Event End', name: 'end', widget: 'datetime', format: "yyyy-MM-dd HH:mm x", date_format: "PPPP", time_format: 'HH:mm' }
      - *Markdown

  - name: 'resources'
    label: 'Resources'
    label_singular: 'Resource'
    folder: '_resources'
    create: true
    slug: '{{slug}}'
    fields: 
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Cover Image', name: 'cover_image', widget: 'image' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: "yyyy-MM-dd x", date_format: "PPPP", time_format: false }
      - { label: 'Excerpt', name: 'excerpt', type: 'text' }
      - *Markdown